"""add_signal_ids_to_strategy_actions

Revision ID: 282ff8c54cd5
Revises: fa46237d584b
Create Date: 2026-07-11 12:08:43.952530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282ff8c54cd5'
down_revision: Union[str, Sequence[str], None] = 'fa46237d584b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('trading_strategy_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signal_ids', sa.Text(), nullable=False, server_default='[]'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_strategy_actions', schema=None) as batch_op:
        batch_op.drop_column('signal_ids')

    # ### end Alembic commands ###
