"""add strategy schedule and execution tables

Revision ID: 5b8f60d83cba
Revises: 04bcce195af7
Create Date: 2026-07-10 14:55:41.042995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8f60d83cba'
down_revision: Union[str, Sequence[str], None] = '04bcce195af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_strategy_executions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.Text(), nullable=False),
    sa.Column('finished_at', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('action_count', sa.Integer(), nullable=False),
    sa.Column('actions_json', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trading_strategy_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_strategy_executions_strategy_name'), ['strategy_name'], unique=False)

    op.create_table('trading_strategy_schedules',
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('cron', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('strategy_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trading_strategy_schedules')
    with op.batch_alter_table('trading_strategy_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_strategy_executions_strategy_name'))

    op.drop_table('trading_strategy_executions')
    # ### end Alembic commands ###
