"""add publish fields to trading_posts

Revision ID: f17522fa040a
Revises: f198dca9a0e0
Create Date: 2026-07-14 14:10:06.707517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f17522fa040a'
down_revision: Union[str, Sequence[str], None] = 'f198dca9a0e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('trading_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_at', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('share_link', sa.String(length=512), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('publish_error', sa.Text(), nullable=False, server_default=''))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_posts', schema=None) as batch_op:
        batch_op.drop_column('publish_error')
        batch_op.drop_column('share_link')
        batch_op.drop_column('published_at')

    # ### end Alembic commands ###
