"""add trading_posts table

Revision ID: f198dca9a0e0
Revises: 47357b4b93e5
Create Date: 2026-07-13 12:57:47.543233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f198dca9a0e0'
down_revision: Union[str, Sequence[str], None] = '47357b4b93e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_posts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('execution_id', sa.String(length=32), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('style', sa.String(length=32), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('post_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trading_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_posts_execution_id'), ['execution_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_posts_execution_id'))

    op.drop_table('trading_posts')
    # ### end Alembic commands ###
