"""unify_reason_and_execution_into_action_records

Revision ID: fa46237d584b
Revises: 5b8f60d83cba
Create Date: 2026-07-11 10:48:43.040433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa46237d584b'
down_revision: Union[str, Sequence[str], None] = '5b8f60d83cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_strategy_actions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('execution_id', sa.String(length=32), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('position_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.Column('reason_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trading_strategy_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_strategy_actions_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trading_strategy_actions_strategy_name'), ['strategy_name'], unique=False)

    with op.batch_alter_table('trading_orders', schema=None) as batch_op:
        batch_op.drop_column('reason')

    with op.batch_alter_table('trading_strategy_executions', schema=None) as batch_op:
        batch_op.drop_column('actions_json')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_strategy_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actions_json', sa.TEXT(), nullable=False))

    with op.batch_alter_table('trading_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.VARCHAR(length=128), nullable=False))

    with op.batch_alter_table('trading_strategy_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_strategy_actions_strategy_name'))
        batch_op.drop_index(batch_op.f('ix_trading_strategy_actions_execution_id'))

    op.drop_table('trading_strategy_actions')
    # ### end Alembic commands ###
